### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by wdturner** [rcos/rcos-handbook#110]
**Description of Issue:**

We need to review the RCOS Handbook to make sure it is in line with RPI's policies.

https://sexualviolence.rpi.edu/sites/default/files/Rensselaer%20Handbook%20of%20Student%20Rights%20%26%20Responsibilities%2C%20November%202017.pdf
https://dotcio.rpi.edu/policy/comec

**Proposed Solution:**

Please describe your proposed solution here (feel free to delete this text)

**Comment by kburk1997** [comment]
Only issue I've found was with failing students upon removal. From the Handbook:
"Student performance in coursework shall be evaluated on an academic basis, not on opinions or conduct in matters unrelated to academic standards." 

Grade penalties on deliverables are compliant with this, as the conduct is in matters related to academic standards and the penalty only applies to the specific deliverable.

There's also a loophole where talks can not violate the Code of Conduct, but still encourage unethical behavior prohibited by the RPI Student Handbook (e.g. a talk on how to use open source to commit identity theft).

Opening a PR to change some things around. Otherwise we are compliant with all of RPI's policies.

**Comment by aeksco** [comment]
Resolved by #111 - closing.
