### ISSUE TITLE
Define the coordinator role and how coordinators are selected

### ISSUE THREAD

**Issue by Bad-Science** [rcos/rcos-handbook#15]
**Description of Issue:**

We do not have a good description for what coordinators actually do, and are not very transparent as to how we select them. Previous attempts had been made to define this, but are incomplete and out of date.

**Proposed Solution:**

A high level description of what a coordinator is should be added, as well as a more in depth section on how to be a good coordinator, and the types of decisions coordinators should made. We should also provide the general criteria of how we select coordinators, and what types of initiative we look for in potential coordinators. Although coordinators are and should be selected behind closed doors, it is important we are transparent as to how we select them.

**Comment by Apexal** [comment]
I am taking ownership of this because the current generation of coordinators will all be leaving in the next 1-3 semesters and I will be the last to leave 😢 We recently selected 2 more Coordinators starting Spring 2021 so onboarding them is the perfect opportunity to document the process for the future.

Also, we can use the API (whichever solution we settle on) to dynamically list the Coordinators on the Handbook page!

**Comment by Apexal** [comment]
Taking this up for real this time since we have new Coordinators once again and the onboarding process will be fresh in my mind!
