### ISSUE TITLE
Add mentor training documentation

### ISSUE THREAD

**Issue by kburk1997** [rcos/rcos-handbook#32]
**Description of Issue:**

Mentor training needs to be completed at the very start of the semester -- we should get documentation on mentor training ASAP.
**Proposed Solution:**

Propose various strategies for mentor training and write up documentation

**Comment by aeksco** [comment]
Just getting a rough list started...

Mentor training should cover (among other things):
- Running small group (stand up, presentation review, etc.)
- Helping in large group (managing noise levels / talking)
- Using Observatory as a Mentor (i.e. verifying students, setting up a small-group, etc.)
- Estimated mentor time commitments (i.e. small group, large group, bi-weekly mentor meetings)
- Protocol for handling CoC violations (i.e. dishonestly, disrespectful behavior, etc.)

**Comment by kburk1997** [comment]
Here are some other things that we could possibly cover:
- Helping with/hosting casual coding sessions/bonus sessions/code jams
- Proposed timeslots for mentor training at the beginning of the semester
- Proposal review/speed dating at the beginning of the semester

**Comment by kochman** [comment]
@aeksco already mentioned presentation reviews in small group, but I want to emphasize that even more. Talking to some of the other mentors this past semester, it was clear that many had no idea what the presentations coming out of their small groups should look like. I think large group suffered as a result. Mentors need to know how to give valuable and constructive feedback to projects before they present to the large group.

**Comment by aeksco** [comment]
Notes from 8/20/18 Coordinator Meeting:


## Mentor Training Notes
- Will need different time slots for mentor training
- Only 5 signed up - and all times conflict
- Adrian started making Mentor training presentation in html
- Converted presentation to HTML5 
- Evaluate how effective Git presentation is
- Make mento training mandatory for anyone new or not mentoring since fall 2017 
- Every small group should have a returning mentor
- Try roving around if you are a returning mentor 
- Try to make welcoming environment to new mentors especially

**Comment by kburk1997** [comment]
Documentation exists
