### ISSUE TITLE
Large Group Restructuring

### ISSUE THREAD

**Issue by vakrao** [rcos/rcos-handbook#96]
**Description of Issue:**
Need to specify how large group will change and how grading will be changed. 

**Proposed Solution:**

One mandatory large group a month - the rest of the Friday's are different bonus sessions (tentatively named this - but might change) for different topics. This will require mentors to know what they want to have bonus sessions for throughout the semester. Also, need to have extra rooms reserved in DCC.  I think that students should be required to go to half of these bonus sessions. We can also count hackathons or any event where learning relating to open-source or computing is occurring.

**Comment by kburk1997** [comment]
For these bonus sessions -- we should definitely cater to a diverse range of abilities, interests, and experience levels. E.g. have bonus sessions covering both basic and advanced topics on the same day so that underclassmen and people who want to explore different fields don't feel completely lost, and upperclassmen and/or more senior members don't get bored. In addition, have bonus sessions focused on non-software and non-coding topics such as hardware, graphic and/or product and/or UX design, project management, open source manufacturing/prototyping, event/meetup organizatoin and technical writing

**Comment by kburk1997** [comment]
We could also toy around with the idea of requiring (or strongly recommending) that students attend at least one non-code bonus session per semester to encourage students to try new things.

Some other things I forgot to cover for bonus session topic ideas:
- Soft skills
- Career prep

**Comment by aeksco** [comment]
Resolved by #111 - closing.
